### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by empijei** [gopherjs/gopherwasm#17]
I found this from [#833](https://github.com/gopherjs/gopherjs/issues/833) and I liked [this idea](https://github.com/gopherjs/gopherjs/issues/833#issuecomment-399498788).

I am particularly interested in making [go-js-dom](https://github.com/dominikh/go-js-dom) work with webassembly.

I see this is a work in progress, I was about to start my own fork but I thought it might be better to cooperate.

Some questions:
* do you need help with this?
* if so, how would you like to proceed?
* any particular issue you need to tackle?
* do you think to just have DOM APIs for WASM it might be better to just write a package independent from gopherjs?

**Comment by hajimehoshi** [comment]
Hi,

Yes, I appreciate your proposal to help, but I think there is no specific tasks so far. This project is work in progress until Go 1.11 is released since Wasm API is not stable yet. I'd appreciate if you find any problems when you use this project.

DOM API or other API are not the target of this project.

**Comment by hajimehoshi** [comment]
Oh I didn't answer your last question:

> do you think to just have DOM APIs for WASM it might be better to just write a package independent from gopherjs?

It might be better, but I don't have bandwidth to make a new package for DOM APIs. How about porting GopherJS's DOM API projects to use GopherWasm?

**Comment by empijei** [comment]
I'll look into it and report back, thanks for your responses
